apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-5"
  annotations:
    argocd/app-name: my-quarkus-app-5-dev
    backstage.io/kubernetes-id: my-quarkus-app-5
    github.com/project-slug: ohthreeinc/backstage-sample-quarkus-app-5
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-dmsnv.dmsnv.sandbox1515.opentlc.com/#https://github.com/ohthreeinc/backstage-sample-quarkus-app-5?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-dmsnv.dmsnv.sandbox1515.opentlc.com/#https://github.com/ohthreeinc/backstage-sample-quarkus-app-5?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "ohthreeinc"
  providesApis:
    - "my-quarkus-app-5"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app-5"
spec:
  type: openapi
  lifecycle: production
  owner: "ohthreeinc"
  definition:
    $text: ./openapi.yaml